### ISSUE TITLE
Define `null`and `undefined` and describe the difference between the two

### ISSUE THREAD

**Issue by ed42311** [Montana-Code-School/interview-questons#16]

**Comment by Olesia13** [comment]
Undefined is a variable that has been declared but has not been assigned value, so has no value.
Null means the value of nothing and it can be assigned to a variable as a representation of no value.
Unassigned variables are initialized by JavaScript with the default value of undefined. Null assignment must be done programmatically.
Undefined is a type itself, while null is an object.

**Comment by ed42311** [comment]
cool now make a branch, add it to answers, format it as markdown push up open a PR, etc

**Comment by ed42311** [comment]
we already got a PR from some Natalie in Florida, pull down master and see if you can expand at all, maybe fix up some formatting
